"""Initial migration

Revision ID: 521884c32959
Revises: 
Create Date: 2026-07-23 22:39:38.963743

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '521884c32959'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('SERVER', 'WORKSTATION', 'NETWORK_DEVICE', 'IOT', 'CLOUD', 'UNKNOWN', name='assettype'), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='assetstatus'), nullable=False),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('os_family', sa.String(length=100), nullable=True),
    sa.Column('network_segment', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('open_ports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('running_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.String(length=50), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('ioc_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('abuse_confidence_score', sa.Integer(), nullable=False),
    sa.Column('vt_malicious_count', sa.Integer(), nullable=False),
    sa.Column('vt_total_count', sa.Integer(), nullable=False),
    sa.Column('otx_pulse_count', sa.Integer(), nullable=False),
    sa.Column('threat_category', sa.String(length=20), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('asn', sa.String(length=50), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('mitre_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('abuseipdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('virustotal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('otx_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_checked', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_intelligence'))
    )
    op.create_index(op.f('ix_threat_intelligence_id'), 'threat_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_ioc_type'), 'threat_intelligence', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_is_malicious'), 'threat_intelligence', ['is_malicious'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_value'), 'threat_intelligence', ['value'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SOC_ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=50), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('notification_prefs', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_ref_id', sa.String(length=100), nullable=True),
    sa.Column('mitre_tactic', sa.String(length=100), nullable=True),
    sa.Column('mitre_technique', sa.String(length=100), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=20), nullable=True),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.String(length=50), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_alerts_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_alerts_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_alerts_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_src_ip'), 'alerts', ['src_ip'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('malware_analyses',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('is_pe', sa.Boolean(), nullable=False),
    sa.Column('pe_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strings_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('yara_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vt_malicious', sa.Integer(), nullable=False),
    sa.Column('vt_total', sa.Integer(), nullable=False),
    sa.Column('vt_permalink', sa.String(length=500), nullable=True),
    sa.Column('vt_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_malware_analyses_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_malware_analyses'))
    )
    op.create_index(op.f('ix_malware_analyses_id'), 'malware_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_malware_analyses_md5'), 'malware_analyses', ['md5'], unique=False)
    op.create_index(op.f('ix_malware_analyses_sha256'), 'malware_analyses', ['sha256'], unique=False)
    op.create_index(op.f('ix_malware_analyses_status'), 'malware_analyses', ['status'], unique=False)
    op.create_table('network_analyses',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.Column('tcp_count', sa.Integer(), nullable=False),
    sa.Column('udp_count', sa.Integer(), nullable=False),
    sa.Column('icmp_count', sa.Integer(), nullable=False),
    sa.Column('other_count', sa.Integer(), nullable=False),
    sa.Column('anomalies_found', sa.Integer(), nullable=False),
    sa.Column('anomaly_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('analyzed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by_id'], ['users.id'], name=op.f('fk_network_analyses_analyzed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_analyses'))
    )
    op.create_index(op.f('ix_network_analyses_id'), 'network_analyses', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.String(length=50), nullable=True),
    sa.Column('read_at', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('phishing_analyses',
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('sender', sa.String(length=500), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=500), nullable=True),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('spf_pass', sa.Boolean(), nullable=True),
    sa.Column('dkim_pass', sa.Boolean(), nullable=True),
    sa.Column('dmarc_pass', sa.Boolean(), nullable=True),
    sa.Column('urls_found', sa.Integer(), nullable=False),
    sa.Column('malicious_urls', sa.Integer(), nullable=False),
    sa.Column('url_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('malicious_attachments', sa.Integer(), nullable=False),
    sa.Column('attachment_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_model_version', sa.String(length=50), nullable=True),
    sa.Column('header_anomalies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('email_path', sa.String(length=500), nullable=True),
    sa.Column('analyzed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by_id'], ['users.id'], name=op.f('fk_phishing_analyses_analyzed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phishing_analyses'))
    )
    op.create_index(op.f('ix_phishing_analyses_id'), 'phishing_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_phishing_analyses_sender'), 'phishing_analyses', ['sender'], unique=False)
    op.create_index(op.f('ix_phishing_analyses_verdict'), 'phishing_analyses', ['verdict'], unique=False)
    op.create_table('reports',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('report_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.String(length=50), nullable=True),
    sa.Column('period_end', sa.String(length=50), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('scans',
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_ip', sa.String(length=45), nullable=False),
    sa.Column('target_ports', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('open_ports_count', sa.Integer(), nullable=False),
    sa.Column('vulnerabilities_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('cvss_max', sa.Float(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('nmap_command', sa.String(length=1000), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('initiated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_scans_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], name=op.f('fk_scans_initiated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_asset_id'), 'scans', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_index(op.f('ix_scans_target_ip'), 'scans', ['target_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_target_ip'), table_name='scans')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_asset_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_phishing_analyses_verdict'), table_name='phishing_analyses')
    op.drop_index(op.f('ix_phishing_analyses_sender'), table_name='phishing_analyses')
    op.drop_index(op.f('ix_phishing_analyses_id'), table_name='phishing_analyses')
    op.drop_table('phishing_analyses')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_network_analyses_id'), table_name='network_analyses')
    op.drop_table('network_analyses')
    op.drop_index(op.f('ix_malware_analyses_status'), table_name='malware_analyses')
    op.drop_index(op.f('ix_malware_analyses_sha256'), table_name='malware_analyses')
    op.drop_index(op.f('ix_malware_analyses_md5'), table_name='malware_analyses')
    op.drop_index(op.f('ix_malware_analyses_id'), table_name='malware_analyses')
    op.drop_table('malware_analyses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_src_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threat_intelligence_value'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_is_malicious'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_ioc_type'), table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_id'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
